Feature/text normalization
alvenirai/punctfix pull request #14
Opened 2023-02-10 11:20 UTC by sorenmulli

I think the warning thing might be über-careful - shouldn't I just remove that?

2023-02-10 11:56 UTC, kshll6 requested changes

2023-02-10 11:56 UTC, kshll6 commented on README.md
> +Models hosted on huggingface! ❤️  🤗
nice

2023-02-10 11:56 UTC, kshll6 commented on punctfix/inference.py
> +    word_normalization_pattern = re.compile(r"[\W_]+")
Maybe just move out of class as constant

2023-02-16 08:45 UTC, sorenmulli commented
Approved, @kshll6?

2023-02-17 16:16 UTC, kshll6 commented
> approved!

2023-02-17 23:54 UTC, kshll6 approved these changes

2023-02-18 08:38 UTC, merged